version: 2
jobs:
  build-publish-trigger:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build image, test it, push it dockerhub, notify dependents
          command: ./pipe_build_up_test.sh

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          filters:
            branches:
              only:
                  - master
